import { useState, useEffect } from 'react'
import { useLang } from '../../context/LanguageContext'

const APP_VERSION = '1.5.0'

const STORAGE_KEY = 'glowmi_last_seen_version'
const ONBOARDING_KEY = 'glowmi_onboarding_seen'

const RELEASE_NOTES = [
  {
    emoji: '🤖',
    title: `What's New in v${APP_VERSION}`,
    titleKr: `v${APP_VERSION} 업데이트 소식`,
    desc: '4 new AI-powered features to supercharge your skincare routine!',
    descKr: 'AI 기능 4가지가 추가되어 스킨케어 루틴을 강화합니다!',
    items: [
      { emoji: '📋', label: 'AI Routine', labelKr: 'AI 루틴 추천', desc: 'Get personalized AM/PM skincare routines generated by AI based on your skin analysis.', descKr: '피부 분석 결과 기반 AI 맞춤 AM/PM 루틴을 추천받으세요.' },
      { emoji: '🧪', label: 'Ingredient Match', labelKr: '성분 매칭', desc: 'AI tells you if a product\'s ingredients match your skin — with a compatibility score.', descKr: 'AI가 제품 성분이 내 피부에 맞는지 점수와 함께 판정합니다.' },
      { emoji: '💬', label: 'AI Chat', labelKr: 'AI 상담', desc: 'Chat with AI about skincare. Gets personalized answers using your skin data.', descKr: 'AI와 스킨케어 상담! 내 피부 데이터를 활용한 맞춤 답변을 받으세요.' },
      { emoji: '📈', label: 'Progress Report', labelKr: '변화 리포트', desc: 'AI compares your before & after photos and gives a detailed skin progress report.', descKr: 'AI가 비포/애프터 사진을 비교해 피부 변화 리포트를 제공합니다.' },
    ],
  },
]

export function shouldShowReleaseNotes() {
  const hasSeenOnboarding = localStorage.getItem(ONBOARDING_KEY)
  if (!hasSeenOnboarding) return false
  const lastVersion = localStorage.getItem(STORAGE_KEY)
  return lastVersion !== APP_VERSION
}

export function markReleaseNotesSeen() {
  localStorage.setItem(STORAGE_KEY, APP_VERSION)
}

export function seedVersionForNewUser() {
  if (!localStorage.getItem(STORAGE_KEY)) {
    localStorage.setItem(STORAGE_KEY, APP_VERSION)
  }
}

export default function ReleaseNotesModal({ onClose }) {
  const [current, setCurrent] = useState(0)
  const { t } = useLang()

  useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [])

  function handleClose() {
    markReleaseNotesSeen()
    onClose()
  }

  const note = RELEASE_NOTES[current]

  return (
    <div className="onboard-overlay" onClick={handleClose}>
      <div className="onboard-modal" onClick={e => e.stopPropagation()}>
        <button className="onboard-skip" onClick={handleClose}>
          {t('Close', '닫기')}
        </button>

        <div className="onboard-slide" key={current}>
          <div className="onboard-emoji">{note.emoji}</div>
          <h2 className="onboard-title">{t(note.title, note.titleKr)}</h2>
          <p className="onboard-desc">{t(note.desc, note.descKr)}</p>

          <div className="onboard-steps">
            {note.items.map((item, i) => (
              <div key={i} className="onboard-step-row">
                <span className="onboard-step-emoji">{item.emoji}</span>
                <div>
                  <div className="onboard-step-label">{t(item.label, item.labelKr)}</div>
                  <div className="onboard-step-sub">{t(item.desc, item.descKr)}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="onboard-nav">
          <div className="onboard-btns">
            <button className="onboard-btn onboard-next" onClick={handleClose}>
              {t('Got it! 👍', '확인 👍')}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
